.TH FOCUSWRITER "1" "Oct 2011" "User Commands"
.SH NAME
focuswriter \- editor allowing monomaniacal writing
.SH SYNOPSIS
.B focuswriter
[\fIfile...\fR]
.SH DESCRIPTION
Qt editing application that takes over the entire screen and provides
a focused monomaniacal writing experience.
Makes the computer into a typewriter, complete with sound effects.
.PP
If in full screen mode, move the mouse to the top of the screen to
activate the menu.
Usage should be self explanatory.
Many configuration options are available.
.SH AUTHOR
Graeme Gott
.SH "REPORTING BUGS"
See http://gottcode.org/focuswriter/
.SH COPYRIGHT
Licensed under the GNU GPL3+.
.SH "SEE ALSO"
No, do not look at anything else.
Get back to writing!
