.TH FOCUSWRITER "1" "April 2021" "General Commands"
.P
.SH "NAME"
.P
focuswriter \- fullscreen word processor
.P
.SH "SYNOPSIS"
.P
\fBfocuswriter\fP [options] [\fIfiles\fP]
.P
.SH "DESCRIPTION"
.P
FocusWriter is a simple, distraction-free word processor. It utilizes a
hide-away interface that you access by moving your mouse to the edges of
the screen, allowing the program to have a familiar look and feel to it
while still getting out of the way so that you can immerse yourself in
your work.
.P
.SH "OPTIONS"
.P
.TP
\fB\-h\fP, \fB\-\-help\fP
Displays help on commandline options.
.TP
\fB\-\-help-all\fP
Displays help including Qt specific options.
.TP
\fB\-v\fP, \fB\-\-version\fP
Displays version information.
.TP
\fIfiles\fP
Files to open in current session.
.P
.SH "SEE ALSO"
.P
\fBqt5options\fP(7)
.P
.SH "REPORTING BUGS"
.P
Report bugs to <focuswriter@bugs.gottcode.org>.
.P
.SH "COPYRIGHT"
Copyright \(co 2008\-2021 Graeme Gott
.P
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.
.P
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
.P
You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
.P
.SH "AUTHOR"
.P
Graeme Gott <graeme@gottcode.org>.
