.TH FOCUSWRITER 1 "April 2021" "FocusWriter 1.7.6" "General Commands Manual"

.SH "NAME"
focuswriter \- fullscreen word processor

.SH "SYNOPSIS"
.B focuswriter
[options]
.RI [ files ]

.SH "DESCRIPTION"
FocusWriter is a simple, distraction-free word processor. It utilizes a
hide-away interface that you access by moving your mouse to the edges of
the screen, allowing the program to have a familiar look and feel to it
while still getting out of the way so that you can immerse yourself in
your work.

.SH "OPTIONS"
.TP
.BR \-h ", " \-\-help
Displays help on commandline options.
.TP
.B \-\-help-all
Displays help including Qt specific options.
.TP
.BR \-v ", " \-\-version
Displays version information.
.TP
.I files
Files to open in current session.

.SH "SEE ALSO"
.BR qt5options (7)

.SH "REPORTING BUGS"
Report bugs to <focuswriter@bugs.gottcode.org>.

.SH "COPYRIGHT"
Copyright \(co 2008-2021 Graeme Gott
.PP
Free use of this software is granted under the terms of the GNU General
Public License version 3 (GPLv3). There is NO WARRANTY, to the extent
permitted by law.

.SH "AUTHOR"
Graeme Gott <graeme@gottcode.org>.
