[General]
LoadColor=#1d1c21

[Background]
Color=#1d1c21
ImageFile=bitterskies.jpg
Type=5

[Foreground]
Color=#ffffff
Margin=65
Opacity=0
Padding=10
Position=0
Rounding=0
RoundingDisabled=10
Width=700

[ForegroundBlur]
Enabled=false
Radius=32

[ForegroundShadow]
Color=#ffffff
Enabled=false
Offset=2
Radius=8

[Spacings]
IndentFirstLine=false
LineSpacing=100
ParagraphAbove=0
ParagraphBelow=0
TabWidth=48

[Text]
Color=#ffffff
Font="Times New Roman,12,-1,5,50,0,0,0,0,0"
Misspelled=#ff0000
