[General]
LoadColor=#5f5f66

[Background]
Color=#5f5f66
ImageFile=enchantment.jpg
Type=5

[Foreground]
Color=#dee9f1
Margin=65
Opacity=25
Padding=10
Position=2
Rounding=0
RoundingDisabled=10
Width=700

[ForegroundBlur]
Enabled=true
Radius=32

[ForegroundShadow]
Color=#000000
Enabled=true
Offset=2
Radius=8

[Spacings]
IndentFirstLine=false
LineSpacing=100
ParagraphAbove=0
ParagraphBelow=0
TabWidth=48

[Text]
Color=#3e3135
Font="Times New Roman,12,-1,5,50,0,0,0,0,0"
Misspelled=#ff0000
